repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.0.0-beta.2
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome"]
  - repo: https://github.com/executablebooks/mdformat
    rev: "0.7.22"
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-config
          - mdformat-ruff
          - mdformat-shfmt
          - mdformat-web
          #
          - mdformat-tables
  - repo: https://github.com/PyCQA/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
      - id: docformatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/openstack/bashate
    rev: "2.1.1"
    hooks:
      - id: bashate
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
